### ISSUE TITLE
Error while Configuring CKAN Fluent with ckanext-Scheming

### ISSUE THREAD

**Issue by kumarvivek1752** [ckan/ckanext-fluent#45]
I'm trying to configure CKAN Fluent with ckanext-Scheming to add extra language fields for datasets and names. The goal is to have multilingual support for dataset titles and resource names. However, when I attempted to implement this configuration, I encountered the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask_debugtoolbar/__init__.py", line 142, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/srv/app/src/ckan/ckan/views/dataset.py", line 584, in post
    pkg_dict = get_action(u'package_create')(context, data_dict)
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckan/ckan/logic/action/create.py", line 192, in package_create
    data, errors = lib_plugins.plugin_validate(
  File "/srv/app/src/ckan/ckan/lib/plugins.py", line 327, in plugin_validate
    result = plugin.validate(context, data_dict, schema, action)
  File "/srv/app/src_extensions/ckanext-scheming/ckanext/scheming/plugins.py", line 312, in validate
    return navl_validate(data_dict, schema, context)
  File "/srv/app/src/ckan/ckan/lib/navl/dictization_functions.py", line 313, in validate
    errors_unflattened = unflatten(errors)
  File "/srv/app/src/ckan/ckan/lib/navl/dictization_functions.py", line 463, in unflatten
    current_pos = current_pos[key]
TypeError: list indices must be integers or slices, not str

```
The error seems to occur during data validation, specifically when calling the `navl_validate` function from the `dictization_functions.py` module. It points to the `unflatten` function, where an attempt to access a list element with a string key is made, resulting in the TypeError.

To add extra language fields for datasets and names, I followed the ckanext-Scheming documentation and configured the schema. I have provided the link to my schema configuration [file here.][1]

Has anyone else encountered a similar issue while configuring CKAN Fluent with ckanext-Scheming? Could you please review my schema configuration and provide any insights or possible solutions to resolve this TypeError? Any help or guidance would be greatly appreciated.

Thank you!

  [1]: https://github.com/kumarvivek1752/ckanext-translate/blob/main/ckanext/translate/schemas/ckan_dataset.yaml

**Comment by kumarvivek1752** [comment]
And my question is, do I have to create a custom validator if I'm configuring ckanext-fluent? I just want to add extra fields for the dataset title and description, such as title en, title fr, title ru, etc., for different languages.
